Dev
Tran-Research-Group/gym-multigrid pull request #58
Opened 2023-11-09 18:34 UTC by miki-yuasa

2023-12-05 16:45 UTC, apurl1 commented on gym_multigrid/envs/maze.py
> +MazeColors: dict[str, NDArray] = {
can we put this in core/constants.py?

2023-12-05 16:46 UTC, apurl1 commented on gym_multigrid/envs/maze.py
> +MazeWorld = World(
can we put this in core/world.py?

2023-12-05 16:47 UTC, apurl1 requested changes
good overall. left suggestions in comments to move some definitions to more appropriate code files.

2024-05-31 21:10 UTC, miki-yuasa commented on gym_multigrid/envs/maze.py
> +MazeColors: dict[str, NDArray] = {
Moved to core/constants.py

2024-05-31 21:10 UTC, miki-yuasa commented on gym_multigrid/envs/maze.py
> +MazeWorld = World(
Moved

2024-06-14 16:51 UTC, apurl1 approved these changes

2024-06-14 16:51 UTC, merged