Feat/wildfire env
Tran-Research-Group/gym-multigrid pull request #86
Opened 2024-08-15 01:11 UTC by npnike10

Contains the following additions
 1. Wildfire fighting environment and auxiliary code
 2. Docstrings for files in core directory of gym_multigrid

2024-11-01 16:16 UTC, miki-yuasa requested changes
I would suggests these changes. Also, we have to somehow resolve the merge conflicts with the dev branch

2024-11-01 16:16 UTC, miki-yuasa commented on README.md
> -## Code conventions
Can you clarify why the code convention was removed?

2024-11-01 16:16 UTC, miki-yuasa commented on gym_multigrid/core/agent.py
>  class CollectActions(enum.IntEnum):
Did you run the test case to see if this change will not break the Collect Env?

2024-11-01 16:16 UTC, miki-yuasa commented on gym_multigrid/envs/wildfire.py
> +    def __init__(
Add type hints to the args to help users make sure what types are accepted

2024-11-01 16:16 UTC, miki-yuasa commented on gym_multigrid/envs/wildfire.py
> +    def reset(self, seed: int | None = None, state=None):
Optional args should be in a dict format
e.g.
```
options: dict[str, Any] = {
"state": None
}
```

2024-11-01 16:16 UTC, miki-yuasa commented on gym_multigrid/core/agent.py
> -
A line is intentionally inserted to separate Python's standard libs and 3rd party libs

2024-11-01 16:16 UTC, miki-yuasa commented on gym_multigrid/core/agent.py
>  from numpy.typing import NDArray
There should be a blank line here to separate the 3rd party libs and our modules

2025-02-13 23:10 UTC, npnike10 commented on README.md
> -## Code conventions
It was moved to Contributing guide in CONTRIBUTING.md. The current main branch also follows this.

2025-02-17 00:31 UTC, npnike10 commented on gym_multigrid/core/agent.py
>  class CollectActions(enum.IntEnum):
I made a couple of changes in collect_game.py for test_collect.py to work with my version of code in this request. One change was making action names uppercase (as suggested by pylint) and other change was adding int(...) around RHS of line 37 in collect_game.py. I've also communicated both changes to Rupal, will update once she replies, if there is anything.

2025-02-17 01:07 UTC, npnike10 commented on gym_multigrid/envs/wildfire.py
> +    def __init__(
added type hints to all args in functions/methods in wildfire.py

2025-02-17 01:11 UTC, npnike10 commented on gym_multigrid/core/agent.py
> -
did this for wildfire.py and agent.py

2025-02-17 01:11 UTC, npnike10 commented on gym_multigrid/core/agent.py
>  from numpy.typing import NDArray
did this for wildfire.py and agent.py

2025-02-17 01:21 UTC, npnike10 commented on gym_multigrid/envs/wildfire.py
> +    def reset(self, seed: int | None = None, state=None):
thanks for catching this. fixed.

2025-02-18 21:50 UTC, miki-yuasa approved these changes

2025-02-18 21:50 UTC, merged